### PR TITLE
Final_submisssion_MSR

### PR DESCRIPTION
**Pull request by shan-mathi**

### CODE REVIEW

**Review by SanjeevKrishnan — CHANGES_REQUESTED** [review]
@shan-mathi Fine Work! Only minor changes:
Move PID_NodeMCU.ino out of the folder.

**Comment by shan-mathi** [comment]
Changes have been made

**Review by SanjeevKrishnan — APPROVED** [review]
Great Work!
@Shubhanshu07 I suggest for merge!

**Comment by agshubhs** [comment]
@shan-mathi Great work guys !
PR looks good to me 
The videos are amazing.

**Pull request merged**
